### ISSUE TITLE
There should be a way to forward the `request_id` header when initializing the client

### ISSUE THREAD

**Issue by Soulou** [Scalingo/go-scalingo#209]
Currently if a project is using this module, we loose track of the request when it is used since no `request_id` can be forwarded.

**Comment by EtienneM** [comment]
At Scalingo we use go-handler to automatically set a request ID:

https://github.com/Scalingo/go-handlers/blob/639d40004569f616e04c5d2d506126d54d667e3f/request_id_middleware.go

We would like to update the `Do` method to take a `context.Context` in argument:

https://github.com/Scalingo/go-scalingo/blob/6714c0fef9c1bb5ff24f7ae80390f56c7bcc1928/http/api_request.go#L70

So that we can set the request ID here (if there is a request ID in the context):

https://github.com/Scalingo/go-scalingo/blob/6714c0fef9c1bb5ff24f7ae80390f56c7bcc1928/http/api_request.go#L105

Fixing this issue will lead to a new major version.
